---
title: "Virome_sinimütsike"
author: "Sinimütsike group"
date: "March 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import

```{r}
library(tidyverse)
library(readr)
library(dplyr)


```


```{r}
library_size <- read_csv("data/library_size.csv")
View(library_size)
phage_counts <- read_csv("data/phage_counts.csv")
View(phage_counts)
```
```{r}
phage_counts %>% 
    group_by(parent_tax_id) %>% 
    summarise(n = n())
```

```{r}
phage_counts %>% group_by(arm) %>% summarise(n=n()) -> query_count
phage_counts %>% group_by(arm, parent_tax_id, timepoint) %>% summarise(n=n()) -> tax_count
tax_count
```

```{r}
sort1 <- tax_count[order(n, arm, decreasing = TRUE), ]
sort2 <- sort1[1:60, ]
sort2
```

```{r}
tax_count %>% 
    group_by(arm, timepoint) %>% 
    top_n(10, n) %>% 
    ggplot(aes(factor(parent_tax_id), n, fill = arm)) +
    geom_col(position = "dodge") +
    facet_wrap(~timepoint)+
    theme(axis.text.x = element_text(angle = 90))
```


```{r}
ggplot(sort2, aes(as.character(parent_tax_id), n, fill=arm))+geom_bar(stat="identity", position="dodge") + labs(x = "parent_tax_id", y = "Count")

```




